FROM node:10.12.0-alpine
ADD ./waitfile /waitfile
RUN chmod +x /waitfile
WORKDIR /home/nodejs/app
ENV NODE_ENV prod
COPY package*.json ./
RUN npm install --only=production
ARG port=80
EXPOSE $port
COPY . ./
CMD /waitfile && node index.js